basePath: /
definitions:
  model.ResponseBody:
    properties:
      fullname:
        type: string
      password:
        type: string
      userID:
        description: XMLName  xml.Name `xml:"data"`
        type: integer
      username:
        type: string
    type: object
  response.ResponseModel:
    properties:
      data: {}
      message:
        type: string
      retCode:
        type: string
    type: object
host: localhost:5555
info:
  contact:
    email: raymond.bago@fortress-asya.com
    name: FDSAP Support
  description: FDSAP swagger template
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API - XML
  version: "1.0"
paths:
  /account/get_user:
    get:
      description: Show all users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseModel'
      summary: Show all users
      tags:
      - Users
swagger: "2.0"
